#!/usr/bin/env python3

"""
Main entry point for starting a training job.
"""

import os
import sys
import argparse
import subprocess
import shutil
import logging
import logging.config

env_types = [
    'append-still',
    'append-spawn',
    'prune-still',
    'prune-spawn',
    'navigate',
]

parser = argparse.ArgumentParser(description="""
    Run agent training using proximal policy optimization.

    This will set up the data/log directories, optionally install any needed
    dependencies, start tensorboard, configure loggers, and start the actual
    training loop. If the data directory already exists, it will prompt for
    whether the existing data should be overwritten or appended. The latter
    allows for training to be restarted if interrupted.
    """)
parser.add_argument('data_dir',
    help="the directory in which to store this run's data")
parser.add_argument('--install', action="store_true",
    help="Set this flag to ensure that all dependencies are installed"
    " before starting the job (helpful for running remotely).")
parser.add_argument('--shutdown', action="store_true",
    help="Shut down the system when the job is complete"
    "(helpful for running remotely).")
parser.add_argument('--port', default=6006, type=int,
    help="Port on which to run tensorboard.")
parser.add_argument('--impact-penalty', default=0.0, type=float)
parser.add_argument('--env-type', choices=env_types)
parser.add_argument('--algo', choices=('ppo', 'dqn', 'ppo-tf'), default='ppo')
args = parser.parse_args()


# Setup the directories

safety_dir = os.path.realpath(os.path.join(__file__, '../'))
data_dir = os.path.realpath(args.data_dir)
job_name = os.path.basename(data_dir)
sys.path.insert(1, safety_dir)  # ensure current directory is on the path
os.chdir(safety_dir)

if os.path.exists(data_dir) and args.data_dir is not None:
    print("The directory '%s' already exists. "
          "Would you like to overwrite the old data, append to it, or abort?" %
          data_dir)
    response = None
    response = 'overwrite' if job_name.startswith('tmp') else None
    while response not in ('overwrite', 'append', 'abort'):
        response = input("(overwrite / append / abort) > ")
    if response == 'overwrite':
        print("Overwriting old data.")
        shutil.rmtree(data_dir)
    elif response == 'abort':
        print("Aborting.")
        exit()

os.makedirs(data_dir, exist_ok=True)
logfile = os.path.join(data_dir, 'training.log')


# Get the environment type from the job name if not otherwise supplied
if args.env_type:
    env_type = args.env_type
else:
    for env_type in env_types:
        if env_type in job_name:
            break
    else:
        env_type = 'prune-still'

assert env_type in env_types


# Setup logging

if not os.path.exists(logfile):
    open(logfile, 'w').close()  # write an empty file
logging_config = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname:8s} {message}',
            'style': '{',
        },
        'dated': {
            'format': '{asctime} {levelname} ({filename}:{lineno}) {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'INFO',
            'stream': 'ext://sys.stdout',
            'formatter': 'simple',
        },
        'logfile': {
            'class': 'logging.FileHandler',
            'level': 'INFO',
            'formatter': 'dated',
            'filename': logfile,
        }
    },
    'loggers': {
        'training': {
            'level': 'INFO',
            'propagate': False,
            'handlers': ['console', 'logfile'],
        },
        'safelife': {
            'level': 'INFO',
            'propagate': False,
            'handlers': ['console', 'logfile'],
        }
    },
    'root': {
        'level': 'WARNING',
        'handlers': ['console', 'logfile'],
    }
}
logging.config.dictConfig(logging_config)


# Install dependencies if they aren't already there

if args.install:
    reqs_file = os.path.join(safety_dir, "requirements.txt")
    subprocess.run("sudo apt-get install ffmpeg --yes".split())
    subprocess.run(["sudo", "pip3", "install", "-r", reqs_file])
# By making the build lib the same as the base folder, the extension
# should just get built into the source directory.
subprocess.run([
    "python3", os.path.join(safety_dir, "setup.py"),
    "build_ext", "--build-lib", safety_dir
])


# Start tensorboard

if args.port:
    tb_proc = subprocess.Popen([
        "tensorboard", "--logdir_spec", job_name + ':' + data_dir, '--port', str(args.port)])


# Start training!

try:
    from training.env_factory import (
        LinearSchedule,
        SafeLifeLevelIterator,
        SwitchingLevelIterator,
        safelife_env_factory
    )
    from safelife.safelife_logger import SafeLifeLogger

    for penalty in [args.impact_penalty]:
        subdir = os.path.join(data_dir, "penalty_{:0.2f}".format(penalty))
        os.makedirs(subdir, exist_ok=True)

        data_logger = SafeLifeLogger(subdir)

        if env_type == 'append-still':
            t_penalty = [1.0e6, 2.0e6]
            t_performance = [1.0e6, 2.0e6]
            level_iterator = SafeLifeLevelIterator('random/append-still-easy.yaml')
            test_levels = 'benchmarks/v1.0/append-still.npz'

        elif env_type == 'prune-still':
            t_penalty = [0.5e6, 1.5e6]
            t_performance = [0.5e6, 1.5e6]
            level_iterator = SafeLifeLevelIterator('random/prune-still-easy.yaml')
            test_levels = 'benchmarks/v1.0/prune-still.npz'

        elif env_type == 'append-spawn':
            # When training in spawn environments, we first pre-train in the
            # static environments for a couple million time steps. This just
            # provides more opportunities for rewards so makes the initial
            # training easier.
            t_penalty = [2.0e6, 3.5e6]
            t_performance = [1.0e6, 2.0e6]
            level_iterator = SwitchingLevelIterator(
                'random/append-still-easy.yaml'
                'random/append-spawn.yaml',
                t_switch=1.5e6,
                logger=data_logger
            )
            test_levels = 'benchmarks/v1.0/append-spawn.npz'

        elif env_type == 'prune-spawn':
            t_penalty = [1.5e6, 2.5e6]
            t_performance = [0.5e6, 1.5e6]
            level_iterator = SwitchingLevelIterator(
                'random/prune-still-easy.yaml'
                'random/prune-spawn.yaml',
                t_switch=2.0e6,
                logger=data_logger
            )
            test_levels = 'benchmarks/v1.0/append-spawn.npz'

        elif env_type == 'navigate':
            t_penalty = [1.0e6, 2.0e6]
            t_performance = [1.0e6, 2.0e6]  # not actually relevant for navigate
            level_iterator = SafeLifeLevelIterator('random/navigation.yaml')
            test_levels = 'benchmarks/v1.0/navigation.npz'
        else:
            logging.error("Unexpected environment type '%s'", env_type)

        training_envs = safelife_env_factory(
            data_logger=data_logger, num_envs=16,
            impact_penalty=LinearSchedule(data_logger, t_penalty, [0, penalty]),
            min_performance=LinearSchedule(data_logger, t_performance, [0.01, 0.5]),
            level_iterator=level_iterator,
        )
        testing_envs = safelife_env_factory(
            data_logger=data_logger, num_envs=5, testing=True,
            level_iterator=SafeLifeLevelIterator(
                test_levels, distinct_levels=5, total_levels=-1)
        )

        if args.algo == 'ppo':
            from training.models import SafeLifePolicyNetwork
            from training.ppo import PPO

            obs_shape = training_envs[0].observation_space.shape
            model = SafeLifePolicyNetwork(obs_shape)
            algo = PPO(
                model,
                training_envs=training_envs,
                testing_envs=testing_envs,
                data_logger=data_logger)
            algo.train(6e6)

        elif args.algo == 'dqn':
            from training.models import SafeLifeQNetwork
            from training.dqn import DQN

            obs_shape = training_envs[0].observation_space.shape
            train_model = SafeLifeQNetwork(obs_shape)
            target_model = SafeLifeQNetwork(obs_shape)
            algo = DQN(
                train_model, target_model,
                training_envs=training_envs,
                testing_envs=testing_envs,
                data_logger=data_logger)
            algo.train(6e6)
        else:
            logging.error("Unexpected algorithm type '%s'", args.algo)


except Exception:
    logging.exception("Ran into an unexpected error. Aborting training.")
finally:
    if args.port:
        tb_proc.kill()
    if args.shutdown:
        # Shutdown in 3 minutes.
        # Enough time to recover if it crashed at the start.
        subprocess.run("sudo shutdown +3".split())
        logging.critical("Shutdown commenced. Exiting to bash.")
        subprocess.run(["bash", "-il"])
