#include <stdint.h>


enum cell_type_bits {
    ALIVE_BIT = 0,
    AGENT_BIT = 1,
    PUSHABLE_BIT = 2,
    PULLABLE_BIT = 15,
    DESTRUCTIBLE_BIT = 3,
    FROZEN_BIT = 4,
    PRESERVING_BIT = 5,
    INHIBITING_BIT = 6,
    SPAWNING_BIT = 7,
    EXIT_BIT = 8,
    COLOR_BIT = 9,
    ORIENTATION_BIT =12,

};

enum cell_types {
    ALIVE = 1 << ALIVE_BIT,
    AGENT = 1 << AGENT_BIT,
    PUSHABLE = 1 << PUSHABLE_BIT,
    PULLABLE = 1 << PULLABLE_BIT,
    DESTRUCTIBLE = 1 << DESTRUCTIBLE_BIT,
    FROZEN = 1 << FROZEN_BIT,
    PRESERVING = 1 << PRESERVING_BIT,
    INHIBITING = 1 << INHIBITING_BIT,
    SPAWNING = 1 << SPAWNING_BIT,
    EXIT = 1 << EXIT_BIT,
    COLORS = 7 << COLOR_BIT,
    ORIENTATION_MASK = 3 << ORIENTATION_BIT,
};

