#!/usr/bin/env python3

import os
import argparse
import datetime
import subprocess


parser = argparse.ArgumentParser()
parser.add_argument('instance_name', help="name of the gcloud instance")
parser.add_argument('run_name', help="a name for the new run")
parser.add_argument('--port', default='6006')
args = parser.parse_args()

full_name = datetime.date.today().isoformat() + '-' + args.run_name

# Copy over the data
safety_dir = os.path.abspath(os.path.join(__file__, '../../'))
ssh_cmd = os.path.abspath(os.path.join(__file__, '../gcloud-ssh'))

result = subprocess.run([
    'rsync', '--rsh', ssh_cmd, '-r', '--exclude=/data',
    safety_dir + '/', args.instance_name + ':~/' + full_name])
if result.returncode != 0:
    exit(result.returncode)

# Start the job. Use tmux to prevent it from dying on hangup.
# Note that if this session is already running, tmux should prevent us from
# running it again.
result = subprocess.run([
    ssh_cmd, args.instance_name, '-L', args.port + ':localhost:6006',
    f"ln -nsf ~/{full_name} ~/current_run; "
    f"tmux new-session -s {args.run_name} "
    f"~/{full_name}/start-job {args.run_name} --install --shutdown"
])
