#! /bin/sh

# A convenience utility to ssh into a gcloud instance.
# Arguments will be parsed just like regular ssh without the need for
# dashes (as in gcloud command line tool).
# Also used as part of the rsync utility.

host="$1"
shift
zone=""
if echo $host | grep -q central || [ "$host" = "pde-5" ] ; then
    zone="--zone us-central1-b"
fi
exec gcloud compute ssh $zone "$host" -- "$@"
